import Button from "@components/Button";
import CodeSvg from "./svgs/code";
import DownloadSvg from "./svgs/download";
import ScanSvg from "./svgs/scan";
import QRCode from "react-qr-code";
import { OtpInput } from "reactjs-otp-input";
import { useState } from "react";
import AuthHeader from "@components/ui/AuthHeader";

export default function TwoFaComponent() {
  const options = [
    {
      title: "Download an authenticator app",
      text: "You need to download google authenticator on your android or iphone.",
      url: DownloadSvg,
      showQr: false,
      code: "",
    },
    {
      title: "Scan the QR code",
      text: "Open your authenticator and scan the code below.",
      url: ScanSvg,
      showQr: true,
      code: "",
    },
    {
      title: "Enter the codes generated by the authenticator",
      text: "Enter the code generated by google authenticator on your android/iphone.",
      url: CodeSvg,
      showQr: false,
      code: "",
    },
  ];
  const [otp, setOtp] = useState("");
  return (
    <div className="auth_shadow bg-white px-4 lg:px-8 pt-10 pb-8 max-w-[500px]  mx-auto w-full">
      <div className="mb-8">
        <AuthHeader title="2FA" text="Protect your account with 2FA Auth" />
      </div>
      <form>
        <div className="grid gap-y-6">
          {options.map((option) => (
            <div key={option.title}>
              <div className="flex gap-x-6 items-center">
                <option.url />
                <div>
                  <p className="text-gray text-sm font-semibold mb-1 ">
                    {option.title}
                  </p>
                  <p className="text-xs font-semibold text-gray/70">
                    {option.text}
                  </p>
                </div>
              </div>
              {option.showQr && (
                <div className="h-28 w-28 mx-auto mt-8">
                  <QRCode
                    size={256}
                    style={{ height: "auto", maxWidth: "100%", width: "100%" }}
                    value={option.code}
                    viewBox={`0 0 256 256`}
                  />
                </div>
              )}
            </div>
          ))}
        </div>
        <div className="w-full mt-8">
          <OtpInput
            value={otp}
            onChange={setOtp}
            numInputs={6}
            separator={<span></span>}
            inputStyle="border !border-main/30 !pb-2 !pt-4 px-1 !w-12 !h-12 rounded focus:border-main/30"
            containerStyle="!flex  gap-x-2 justify-center"
            placeholder={"_"}
          />
        </div>
        <div className="mt-10 flex gap-x-4 items-center">
          <Button text={"Skip"} variant="outline" /> <Button text={"Proceed"} />
        </div>
      </form>
    </div>
  );
}
